<center><img src="Array-in-Pic.jpg"></img></center>
<p><center><b>Convert the Above Picture into the Array</b></center></p>
<p><center>Irrespective of their color Slice them</center></p>

In [2]:
import numpy as np


PicArray = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],
                     [21, 22, 23, 24, 25],
                     [26, 27, 28, 29, 30]])
PicArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [34]:
print(PicArray[0,1])
print(PicArray[1,2])
print(PicArray[2,3])
print(PicArray[3,4])
        # or 
# PicArray[[0, 1, 2, 3],[1, 2, 3, 4]]   

2
8
14
20


In [30]:
PicArray[[2,3],0:2]       # or PicArray[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [18]:
PicArray[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])