In [1]:
import numpy as np

# Load Data From File

In [5]:
FileData = np.genfromtxt("data.txt", delimiter = ",")

FileData = FileData.astype('int32')
print(FileData)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking & Advance Indexing

In [24]:
FileData > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [25]:
FileData[FileData > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

# Index with a List in NumPy

In [43]:
l = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [11, 22, 33, 44, 55, 66, 77, 88, 99, 1010]])
print(l)
print()
print("Multiple Indexs:",l[0,[1, 2, 8]])

[[   1    2    3    4    5    6    7    8    9   10]
 [  11   22   33   44   55   66   77   88   99 1010]]
Multiple Indexs: [2 3 9]


In [44]:
for index,a in enumerate(l):
    print(index, a)

0 [ 1  2  3  4  5  6  7  8  9 10]
1 [  11   22   33   44   55   66   77   88   99 1010]


# Comparision in Columns 

In [35]:
np.any(FileData > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [22]:
np.all(FileData > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [23]:
np.all(FileData > 50, axis = 1)

array([False, False, False])

In [51]:
FileData[(FileData>50) & (FileData<100)]

array([75, 75, 55, 78, 76, 88])